[project]
name = "object-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.16.5",
    "asyncpg==0.30.0",
    "confluent-kafka[protobuf,schemaregistry]==2.11.1",
    "fastapi==0.116.1",
    "grpcio==1.64.1",
    "protobuf==5.29.5",
    "pydantic==2.11.7",
    "pydantic-settings==2.10.1",
    "pyjwt==2.10.1",
    "python-keycloak==5.8.1",
    "sqlalchemy[asyncio]==2.0.43",
    "uvicorn==0.35.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "grpcio-tools>=1.64.1",
    "mypy==1.17.1",
    "pre-commit>=4.3.0",
    "ty>=0.0.1a19",
    "types-cachetools==6.2.0.20250827",
]
lint = [
    "ruff==0.12.11",
]
tests = [
    "httpx==0.28.1",
    "pytest==8.4.1",
    "pytest-asyncio==1.1.0",
    "pytest-cov==6.2.1",
    "testcontainers==4.12.0",
]
security = [
    "pip-audit==2.9.0",
]
migrations = [
    "alembic>=1.16.5",
    "asyncpg==0.30.0",
    "pydantic-settings>=2.10.1",
    "sqlalchemy[asyncio]>=2.0.43",
]
