[project]
name = "object-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.14.0",
    "annotated-types==0.7.0",
    "anyio==4.7.0",
    "asyncpg==0.30.0",
    "click==8.1.7",
    "colorama==0.4.6",
    "confluent-kafka==2.7.0",
    "exceptiongroup==1.2.2",
    "fastapi==0.115.6",
    "greenlet==3.1.1",
    "h11==0.14.0",
    "idna==3.10",
    "mako==1.3.8",
    "markupsafe==3.0.2",
    "protobuf==5.29.2",
    "psycopg2-binary==2.9.10",
    "pydantic==2.10.3",
    "pydantic-core==2.27.1",
    "pydantic-settings==2.7.1",
    "python-dotenv==1.0.1",
    "python-keycloak==5.1.1",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.36",
    "sqlmodel==0.0.22",
    "starlette==0.41.3",
    "typing-extensions==4.12.2",
    "uvicorn==0.34.0",
]

[dependency-groups]
dev = [
]
lint = [
    "ruff==0.9.1",
]
tests = [
]
security = [
    "pip-audit==2.7.3",
]
migrations = [
    "alembic==1.14.0",
    "psycopg2-binary==2.9.10",
    "sqlmodel==0.0.22",
]
