[project]
name = "object-templates"
version = "3.0.24"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.16.5",
    "asyncpg==0.30.0",
    "confluent-kafka[protobuf,schemaregistry]==2.11.1",
    "dishka==1.7.2",
    "fastapi==0.117.1",
    "grpcio==1.75.1",
    "pandas==2.3.2",
    "protobuf==6.32.1",
    "pydantic==2.11.9",
    "pydantic-settings==2.11.0",
    "pyjwt==2.10.1",
    "python-keycloak==5.8.1",
    "python-multipart==0.0.20",
    "sqlalchemy[asyncio]==2.0.43",
    "uvicorn==0.37.0",
    "xlsxwriter==3.2.9",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "grpcio-tools>=1.75.1",
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "ty>=0.0.1a21",
    "types-cachetools==6.2.0.20250827",
]
lint = [
    "ruff==0.13.2",
]
tests = [
    "httpx==0.28.1",
    "pytest==8.4.2",
    "pytest-asyncio==1.2.0",
    "pytest-cov==7.0.0",
    "testcontainers==4.13.1",
]
security = [
    "pip-audit==2.9.0",
]
migrations = [
    "alembic>=1.16.5",
    "asyncpg==0.30.0",
    "pydantic-settings>=2.10.1",
    "sqlalchemy[asyncio]>=2.0.43",
]
