[project]
name = "object-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.14.0",
    "asyncpg==0.30.0",
    "confluent-kafka==2.8.2",
    "fastapi==0.115.12",
    "grpcio==1.64.1",
    "protobuf==5.29.3",
    "pydantic==2.10.6",
    "pydantic-settings==2.7.1",
    "python-keycloak==5.3.1",
    "sqlalchemy[asyncio]==2.0.37",
    "uvicorn==0.34.0",
]

[dependency-groups]
dev = [
    "mypy==1.15.0",
    "pre-commit==4.2.0",
]
lint = [
    "ruff==0.11.2",
]
tests = [
    "httpx==0.28.1",
    "pytest==8.3.5",
    "pytest-asyncio==0.26.0",
    "testcontainers==4.9.2",
]
security = [
    "pip-audit==2.7.3",
]
migrations = [
    "alembic==1.14.0",
    "asyncpg==0.30.0",
    "pydantic-settings==2.7.1",
    "sqlalchemy==2.0.37",
]
