[project]
name = "object-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.14.0",
    "asyncpg==0.30.0",
    "confluent-kafka==2.8.0",
    "fastapi==0.115.6",
    "grpcio==1.64.1",
    "protobuf==5.29.3",
    "pydantic==2.10.5",
    "pydantic-settings==2.7.1",
    "python-keycloak==5.1.1",
    "sqlalchemy[asyncio]==2.0.37",
    "uvicorn==0.34.0",
]

[dependency-groups]
dev = [
]
lint = [
    "ruff==0.9.1",
]
tests = [
]
security = [
    "pip-audit==2.7.3",
]
migrations = [
    "alembic==1.14.0",
    "asyncpg==0.30.0",
    "sqlalchemy==2.0.37",
    "pydantic-settings==2.7.1",
]
