[project]
name = "object-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.16.4",
    "asyncpg==0.30.0",
    "confluent-kafka==2.11.0",
    "fastapi==0.116.1",
    "grpcio==1.64.1",
    "protobuf==5.29.3",
    "pydantic==2.11.7",
    "pydantic-settings==2.10.1",
    "python-keycloak==5.7.0",
    "sqlalchemy[asyncio]==2.0.43",
    "uvicorn==0.35.0",
]

[dependency-groups]
dev = [
    "mypy==1.17.1",
    "pre-commit>=4.3.0"
]
lint = [
    "ruff==0.12.8",
]
tests = [
    "httpx==0.28.1",
    "pytest==8.4.1",
    "pytest-asyncio==1.1.0",
    "testcontainers==4.12.0",
]
security = [
    "pip-audit==2.7.3",
]
migrations = [
    "alembic>=1.16.4",
    "asyncpg==0.30.0",
    "pydantic-settings>=2.10.1",
    "sqlalchemy[asyncio]>=2.0.43",
]
